@HOST=http://localhost:3333

### -------------------------- Request --------------------------------------

### ========== List Requests ==========
GET {{HOST}}/requests/0x8e7C04aef5EaD2C512b2d18d71AC3b25d8eD21ce

### ========== Create Request ==========
POST {{HOST}}/requests/create/
Content-Type: application/json

{
    "address": "0x608812286c676b0e6ac80AD8af4D201ea677Dc63",
    "name": "Dr. Tito",
    "description": "Can I access your data?"
}

### ========== Answer Request ==========
POST {{HOST}}/requests/answer/
Content-Type: application/json

{
    "id": 13,
    "answer": true
}

### ==========  Check Request Answer ==========
GET {{HOST}}/requests/answer/13
Authorization: 53e52d15-0952-4a87-a99a-c970e8771f2b
Content-Type: application/json
