@HOST=http://localhost:3333

### -------------------------- Request --------------------------------------

### ========== List Requests ==========
GET {{HOST}}/requests/0x133D5D2a0965408c6f9a2797c825E3E797BE234C

### ========== Create Request ==========
POST {{HOST}}/requests/create/
Content-Type: application/json

{
    "address": "0x133D5D2a0965408c6f9a2797c825E3E797BE234C",
    "name": "Dr. Tito",
    "description": "Can I access your data?"
}

### ========== Answer Request ==========
POST {{HOST}}/requests/answer/
Content-Type: application/json

{
    "id": 2,
    "answer": false
}

### ==========  Check Request Answer ==========
GET {{HOST}}/requests/answer/5
Authorization: c210f438-7211-45c9-9d16-dc0a0a7a1302
Content-Type: application/json
